### ISSUE TITLE
A question about setting up workspace

### ISSUE THREAD

**Issue by KailinTong** [KumarRobotics/conformal_lattice_planner#1]

**Comment by KailinTong** [comment]
Dear Ke,

many thanks for your great work!

I would like to reproduce your work.
I read the instruction for the workspace setup, it seems that all dependencies should be installed again.

I have Carla 0.96 in docker and ros melodic on my machine already.

Is there any simple approach for me to set up the workspace?

Can I just install Boost 1.69.0 and  PCL 1.9.1?

Thanks a lot!

Best regards,
Kailin

**Comment by ke-sun** [comment]
I think the problem is ROS and PCL depends on Boost. 
Depending on which version of Linux you are using, Boost 1.69 may not be the default one.
Therefore, installing binary ROS and PCL directly from apt may not work.
What I tried was to compile them from source and explicitly point to Boost 1.69.

**Comment by KailinTong** [comment]
Hi,

I am using Ubuntu 18.04, the default boost is 1.65.1.

Are there any solutions for that?  Cause this will make it difficult to deploy on different machines.
And are there some ways that I can extract the module of trajectory planning?

I potentially like to reproduce this work in Autoware.

**Comment by ke-sun** [comment]
Given that the implementation is tightly coupled with Carla APIs, I would say it is hard to just reuse the trajectory planning part with some other simulators. In your case, it's probably easier to just re-implement the algorithm following the paper :disappointed: .

**Comment by KailinTong** [comment]
Thanks a lot for your answer!

Anyway, your paper is inspiring. I have an idea of using reinforcement learning instead of IDM.
Are you trying to extend this work in this direction?

**Comment by ke-sun** [comment]
Thanks for being interested in our work.

Sounds like an interesting idea. But we are not working on improving trajectory planning.
We are currently trying to model the uncertainty in traffic dynamics.
