### ISSUE TITLE
A question about the algorithm

### ISSUE THREAD

**Issue by KailinTong** [KumarRobotics/conformal_lattice_planner#2]
Dear Ke,

could you pleaes tell which part of your code corresponds to this Directed-graph Map Construction in your paper?

many thanks!

Sincerly, Kailin

**Comment by ke-sun** [comment]
Take a look at the following files.
https://github.com/KumarRobotics/conformal_lattice_planner/blob/master/src/planner/common/lattice.h  
https://github.com/KumarRobotics/conformal_lattice_planner/blob/master/src/planner/common/lattice_inst.h

**Comment by KailinTong** [comment]
Thanks a lot!
