### ISSUE TITLE
A question about occupancy during search

### ISSUE THREAD

**Issue by KailinTong** [KumarRobotics/conformal_lattice_planner#3]
Dear Ke,

I am attempting to implement your code into Python.

Firstly, as far as I understand, by using the speed feedback policy, the search is running in the scheme of Spatial Lattice.
However, the prediction of other agents (or the IDM modeling of other agents) is based on the time axle.
How did you map the position of other agents into the occupancy of spatial lattice?
In the best case, could you tell me which part of the code is doing this?

Secondly, during a search in the spatiotemporal lattice, I found that if the motion primitive is too big ( expansion of distance/time is too big), the ego-motion might "jump" over the obstacle vehicle, which is not realistic.
For example, in a car-following scenario, motion primitive (endpoint) jumps over the car in front of the ego vehicle.
I hope you understand my question, and could you share your experience about how to deal with this?

Best regards,
Kailin

**Comment by ke-sun** [comment]
> Firstly, as far as I understand, by using the speed feedback policy, the search is running in the scheme of Spatial Lattice.
> However, the prediction of other agents (or the IDM modeling of other agents) is based on the time axle.
> How did you map the position of other agents into the occupancy of spatial lattice?
> In the best case, could you tell me which part of the code is doing this?

Take a look at the function `registerVehicles` in `trafficLattice.cpp`.
https://github.com/KumarRobotics/conformal_lattice_planner/blob/56e878a5ccb9daca2bb77bd47cbbfb097b412e2d/src/planner/common/traffic_lattice.cpp#L842
 
> Secondly, during a search in the spatiotemporal lattice, I found that if the motion primitive is too big ( expansion of distance/time is too big), the ego-motion might "jump" over the obstacle vehicle, which is not realistic.
> For example, in a car-following scenario, motion primitive (endpoint) jumps over the car in front of the ego vehicle.
> I hope you understand my question, and could you share your experience about how to deal with this?

I assume the "motion primitive" you are referring to is the path. It is fine to have a path overlap with other agent vehicles.  In the setting of a spatiotemporal lattice planner, one still have to search over different accelerations over the same path to have trajectories, which is actually used to check collisions. In the case that the ego can still "jump over" other agents while following a trajectory, it might indicate that the simulation time resolution is too large.
